import type { LessonContent } from "../lesson-types";

export const deepLearning: Record<string, LessonContent> = {
  tensors: {
    hook: "Every photo, sentence, and song a neural network has ever touched was turned into a grid of numbers first. Learn to read those grids and the rest of deep learning stops being magic.",
    blocks: [
      { t: "p", text: "Module 01 said a neuron multiplies inputs by weights and adds them up. Real networks do that for millions of neurons at once, and the only way to do it fast is to stop thinking about single numbers and start thinking in **arrays of numbers**. Those arrays have names." },
      { t: "terms", items: [
        { term: "Scalar", def: "A single number. A learning rate of `0.001` is a scalar. Shape: `()`." },
        { term: "Vector", def: "A list of numbers. One pixel's color `[0.9, 0.2, 0.1]` is a vector of length 3. Shape: `(3,)`." },
        { term: "Matrix", def: "A grid with rows and columns. A layer's weights are a matrix: one row per output neuron, one column per input. Shape: `(out, in)`." },
        { term: "Tensor", def: "The general word for an array with any number of dimensions. A batch of 32 color photos at 224 × 224 is a 4-D tensor of shape `(32, 3, 224, 224)`." },
      ] },
      { t: "h", text: "Shape is the first thing engineers check" },
      { t: "p", text: "The **shape** of a tensor lists how big each dimension is. Most real bugs in deep learning code aren't wrong math. They're shapes that don't line up. Reading a shape tells you what the tensor *means*." },
      { t: "example", label: "Reading shapes", text: "(32, 3, 224, 224)  → 32 images, 3 color channels, 224 rows, 224 columns\n(8, 512)           → 8 sentences, each 512 tokens long (token IDs)\n(8, 512, 768)      → the same 8 sentences after embedding: 768 numbers per token\n(768, 3072)        → a weight matrix that maps 768 inputs to 3,072 outputs" },
      { t: "h", text: "A whole layer is one matrix multiply" },
      { t: "p", text: "Here's the trick that makes deep learning practical. If you stack a layer's weights into a matrix **W** and the inputs into a vector **x**, then *every* neuron's weighted sum is computed at once by a single **matrix multiplication**: **y = Wx + b**. Each row of W is one neuron's weights. The dot product of that row with x is that neuron's sum." },
      { t: "example", label: "2 neurons, 3 inputs", text: "W = [[ 0.5, -1.0,  2.0],     x = [1, 2, 3]     b = [0.1, -0.2]\n     [ 1.5,  0.0, -0.5]]\n\nrow 1: 0.5·1 + (−1.0)·2 + 2.0·3 = 4.5   → 4.5 + 0.1 = 4.6\nrow 2: 1.5·1 +   0.0·2 + (−0.5)·3 = 0.0 → 0.0 − 0.2 = −0.2\n\ny = [4.6, −0.2]" },
      { t: "p", text: "The rule for multiplying: a `(m, n)` matrix times an `(n,)` vector gives an `(m,)` vector. The inner dimensions must match. A `(768, 3072)` matrix can't multiply a vector of length 512, and that error message is one every ML engineer has seen a thousand times." },
      { t: "h", text: "Why GPUs" },
      { t: "p", text: "A matrix multiply is millions of independent multiply-adds. A CPU has a handful of powerful cores. A GPU has thousands of simpler ones that can each take a slice of the grid at the same time. That's the whole reason AI training runs on graphics cards: the math of a neural network happens to be the same math as shading millions of pixels." },
      { t: "code", label: "The same layer in PyTorch", lang: "python", text: "import torch\n\nx = torch.randn(32, 768)          # a batch of 32 inputs, 768 features each\nlayer = torch.nn.Linear(768, 3072) # weight shape (3072, 768), bias shape (3072,)\ny = layer(x)                        # y = x @ W.T + b\nprint(y.shape)                      # torch.Size([32, 3072])" },
      { t: "note", kind: "key", title: "Batches add a dimension", text: "Networks process many examples at once. Adding a **batch** dimension in front turns a vector-times-matrix into a matrix-times-matrix, which GPUs handle even more efficiently. That leading `32` in the shapes above is the batch size." },
      { t: "note", kind: "try", title: "Count it yourself", text: "A `Linear(768, 3072)` layer has 768 × 3,072 weights plus 3,072 biases: **2,362,368 parameters**. You'll count an entire language model this way in Module 07." },
    ],
    takeaways: [
      "Scalars, vectors, matrices, and tensors are arrays with 0, 1, 2, and n dimensions.",
      "A tensor's shape tells you what it represents. Mismatched shapes are the most common bug.",
      "A whole layer is one matrix multiply: y = Wx + b.",
      "GPUs win because matrix multiplies are millions of independent multiply-adds.",
    ],
    quiz: [
      { q: "A tensor has shape (16, 3, 64, 64). What is it most likely to be?", options: ["16 color images that are 64 × 64 pixels", "A 64-layer network with 16 neurons", "3 sentences of 64 tokens", "A single grayscale image"], answer: 0, why: "Batch first, then 3 color channels, then height and width. That's the standard image layout." },
      { q: "A weight matrix W has shape (10, 4). What does y = Wx need, and what comes out?", options: ["x of length 10, y of length 4", "x of length 4, y of length 10", "x of length 40, y of length 1", "Any x; y has length 14"], answer: 1, why: "A (10, 4) matrix takes 4 inputs and produces 10 outputs. Inner dimensions must match." },
      { q: "How many parameters are in a fully connected layer from 100 inputs to 50 outputs, with biases?", options: ["150", "5,000", "5,050", "5,100"], answer: 2, why: "100 × 50 = 5,000 weights, plus 50 biases, one per output neuron." },
      { q: "Why does deep learning run so much faster on GPUs than CPUs?", options: ["GPUs have more memory than any CPU", "Neural networks are mostly matrix multiplies, which split into thousands of parallel multiply-adds", "GPUs use a different kind of math", "CPUs can't do decimals"], answer: 1, why: "The work is massively parallel, and GPUs have thousands of cores built for exactly that." },
    ],
  },

  "loss-and-gradients": {
    hook: "Training a network is like hiking down a mountain in thick fog with a broken map. You can't see the valley. You can only feel which way the ground slopes under your feet.",
    blocks: [
      { t: "p", text: "Before a model can improve, it needs one number that says *how bad* it is right now. That number is the **loss**. Training is the search for weights that make the loss small. To search efficiently, the model needs the **gradient**: which direction to nudge every weight, and how hard." },
      { t: "h", text: "Two loss functions that run the world" },
      { t: "terms", items: [
        { term: "Mean squared error", def: "For predicting numbers. Square each error and average: `MSE = mean((ŷ − y)²)`. Squaring makes big misses hurt much more than small ones." },
        { term: "Cross-entropy", def: "For picking a category, including the next token. `loss = −log(p_correct)`, where p_correct is the probability the model gave the right answer. Every language model is trained on this." },
      ] },
      { t: "example", label: "Why cross-entropy punishes confident mistakes", text: "model gives the right answer p = 0.90 → loss = −log(0.90) = 0.105\nmodel gives the right answer p = 0.50 → loss = −log(0.50) = 0.693\nmodel gives the right answer p = 0.01 → loss = −log(0.01) = 4.605\n\nBeing confidently wrong costs 44× more than being nearly right." },
      { t: "h", text: "The derivative: slope under your feet" },
      { t: "p", text: "A **derivative** measures how much the output changes when you nudge an input a tiny bit. If increasing a weight by 0.001 increases the loss by 0.003, the derivative of the loss with respect to that weight is about **3**. Positive slope means \"this weight is pushing the loss up, so turn it down.\"" },
      { t: "p", text: "A network has many weights, so it needs many derivatives, one per weight. Collected into a vector, they're called the **gradient**, written **∇L**. The gradient points in the direction where the loss rises fastest. So you step the opposite way:" },
      { t: "example", label: "The gradient descent update", text: "w_new = w_old − learning_rate × ∂L/∂w\n\nExample: w = 2.0, ∂L/∂w = 3.0, learning rate = 0.1\nw_new = 2.0 − 0.1 × 3.0 = 1.7" },
      { t: "h", text: "The chain rule: blame flows backward" },
      { t: "p", text: "A deep network is functions inside functions: the loss depends on the output, which depends on the last layer, which depends on the layer before. The **chain rule** says the derivative through a chain is the product of each link's derivative. If *a* affects *b* and *b* affects the loss, then **∂L/∂a = ∂L/∂b × ∂b/∂a**. That one rule is what makes training a 100-layer network possible, and the next lesson walks through it with real numbers." },
      { t: "h", text: "Valleys aren't always simple" },
      { t: "list", items: [
        "**Local minima:** dips that aren't the lowest point. In very high dimensions these are less of a trap than people once feared, because some direction almost always still slopes down.",
        "**Saddle points:** flat in one direction, sloped in another. Plain gradient descent slows to a crawl here, which is one reason better optimizers exist.",
        "**Exploding and vanishing gradients:** multiply many small derivatives and the signal shrinks to nothing; multiply many large ones and it blows up. Careful initialization, normalization layers, and residual connections were invented to fix this.",
      ] },
      { t: "note", kind: "key", title: "Nobody writes derivatives by hand anymore", text: "Frameworks like PyTorch and JAX use **automatic differentiation**: they record every operation in the forward pass, then apply the chain rule backward automatically. One line, `loss.backward()`, computes the gradient for billions of weights." },
    ],
    takeaways: [
      "Loss is one number for how wrong the model is. MSE for numbers, cross-entropy for categories and tokens.",
      "A derivative is a slope. The gradient is every weight's slope at once.",
      "Gradient descent steps opposite the gradient: w ← w − η∇L.",
      "The chain rule multiplies derivatives through layers, which is how blame reaches early weights.",
    ],
    quiz: [
      { q: "A language model gave the correct next token a probability of 0.25. What's the cross-entropy loss for that token?", options: ["0.25", "−log(0.25) ≈ 1.39", "0.75", "log(0.25) ≈ −1.39"], answer: 1, why: "Cross-entropy is −log of the probability assigned to the correct answer. Lower probability means higher loss." },
      { q: "The derivative of the loss with respect to a weight is −4. Using gradient descent, what should happen to that weight?", options: ["Decrease it", "Increase it", "Leave it alone", "Set it to −4"], answer: 1, why: "w_new = w − η·(−4) = w + 4η. A negative slope means raising the weight lowers the loss." },
      { q: "Why is the chain rule essential for training deep networks?", options: ["It removes the need for a loss function", "It lets the error signal be passed back through each layer by multiplying local derivatives", "It makes the network run faster at inference time", "It prevents overfitting"], answer: 1, why: "Each layer's contribution to the loss is found by chaining local derivatives backward." },
      { q: "Gradients get smaller and smaller as they pass back through a 50-layer network, so early layers barely learn. What's this called?", options: ["Overfitting", "The vanishing gradient problem", "Gradient clipping", "Mode collapse"], answer: 1, why: "Multiplying many derivatives smaller than 1 shrinks the signal toward zero." },
    ],
  },

  "backprop-by-hand": {
    hook: "Backpropagation sounds like advanced calculus. It's really just bookkeeping: run forward, write down every number, then walk backward multiplying slopes. You can do it with a calculator.",
    blocks: [
      { t: "p", text: "Let's train the smallest network that still needs the chain rule: one input, one hidden neuron, one output. Every step below is exactly what PyTorch does on every one of billions of weights, every training step." },
      { t: "example", label: "The network", text: "h = relu(w₁ · x + b₁)        hidden neuron\nŷ = w₂ · h + b₂              output\nL = (ŷ − y)²                 squared error" },
      { t: "h", text: "1. Forward pass: compute and record" },
      { t: "example", label: "With x = 2, y = 3, w₁ = 0.5, b₁ = 0, w₂ = 1.0, b₂ = 0", text: "z = w₁·x + b₁ = 0.5·2 + 0 = 1.0\nh = relu(1.0)       = 1.0\nŷ = w₂·h + b₂ = 1.0·1.0 + 0 = 1.0\nL = (1.0 − 3)²      = 4.0" },
      { t: "h", text: "2. Backward pass: chain the slopes" },
      { t: "p", text: "Start at the loss and ask each step, \"how much did you change the thing after you?\" Then multiply." },
      { t: "example", label: "Local derivatives, then the chain", text: "∂L/∂ŷ  = 2(ŷ − y)      = 2(1 − 3)   = −4\n∂L/∂w₂ = ∂L/∂ŷ · h      = −4 · 1.0   = −4\n∂L/∂b₂ = ∂L/∂ŷ · 1      =              −4\n∂L/∂h  = ∂L/∂ŷ · w₂     = −4 · 1.0   = −4\n∂L/∂z  = ∂L/∂h · relu′(z) = −4 · 1   = −4   (relu′ is 1 when z > 0)\n∂L/∂w₁ = ∂L/∂z · x      = −4 · 2     = −8\n∂L/∂b₁ = ∂L/∂z · 1      =              −4" },
      { t: "h", text: "3. Update every weight" },
      { t: "example", label: "Learning rate η = 0.05", text: "w₁ = 0.5 − 0.05·(−8) = 0.90\nb₁ = 0.0 − 0.05·(−4) = 0.20\nw₂ = 1.0 − 0.05·(−4) = 1.20\nb₂ = 0.0 − 0.05·(−4) = 0.20\n\nNew forward pass: z = 2.0, h = 2.0, ŷ = 2.60, L = 0.16   (down from 4.0)" },
      { t: "p", text: "One step cut the loss by 96%. Notice that **w₁ moved the most** because its gradient was −8: the input x = 2 doubled its influence. Backprop automatically gives more blame to the weights that mattered more." },
      { t: "widget", id: "backprop" },
      { t: "h", text: "Why ReLU matters here" },
      { t: "p", text: "If z had been negative, relu′(z) = 0 and the whole chain from there back would be zero. That neuron would learn nothing from this example. A neuron stuck with negative z on every input is called a **dead ReLU**, and it's one reason variants like GELU, used in most transformers, exist." },
      { t: "code", label: "The same thing, automatically", lang: "python", text: "import torch\n\nw1, b1, w2, b2 = (torch.tensor(v, requires_grad=True) for v in (0.5, 0.0, 1.0, 0.0))\nx, y = torch.tensor(2.0), torch.tensor(3.0)\n\nh = torch.relu(w1 * x + b1)\nloss = (w2 * h + b2 - y) ** 2\nloss.backward()\n\nprint(w1.grad, w2.grad)   # tensor(-8.)  tensor(-4.)  ← matches the hand calculation" },
      { t: "note", kind: "key", title: "Forward stores, backward reuses", text: "The backward pass needs the values from the forward pass (h, x, z). That's why training uses far more memory than running a model: every intermediate value, called an **activation**, is kept until the backward pass is done." },
    ],
    takeaways: [
      "Forward pass: compute and save every intermediate value.",
      "Backward pass: start at ∂L/∂ŷ and multiply local derivatives back through each operation.",
      "Each weight's gradient is its share of the blame. Bigger inputs mean bigger gradients.",
      "Training needs extra memory because activations are stored for the backward pass.",
    ],
    quiz: [
      { q: "In the worked example, why was ∂L/∂w₁ (−8) twice as large as ∂L/∂b₁ (−4)?", options: ["Biases always get half the gradient", "∂z/∂w₁ = x = 2, while ∂z/∂b₁ = 1", "The learning rate doubled it", "w₁ started smaller"], answer: 1, why: "The local derivative of z = w₁x + b₁ with respect to w₁ is x. The input scales the weight's gradient." },
      { q: "A hidden ReLU neuron has z = −1.5 for a training example. What gradient flows back to its incoming weights from that example?", options: ["The full gradient", "Half the gradient", "Zero", "A negative copy of the gradient"], answer: 2, why: "ReLU's derivative is 0 for negative inputs, so the chain is multiplied by zero." },
      { q: "Why does training a model use much more memory than running it?", options: ["Training uses bigger numbers", "Activations from the forward pass must be stored for the backward pass, plus gradients and optimizer state", "The model is copied to every GPU core", "Training data is loaded all at once"], answer: 1, why: "Backprop reuses forward values, and every weight also needs a gradient and optimizer state." },
      { q: "ŷ = 5, y = 2, loss = (ŷ − y)². What is ∂L/∂ŷ?", options: ["3", "6", "9", "−6"], answer: 1, why: "∂L/∂ŷ = 2(ŷ − y) = 2 · 3 = 6." },
    ],
  },

  optimizers: {
    hook: "Same model, same data. One engineer's run converges overnight; another's never learns anything. Often the only difference is a single number: the learning rate.",
    blocks: [
      { t: "p", text: "Gradient descent tells you which way is downhill. An **optimizer** decides how big a step to take and how to use the history of past steps. The choice of optimizer and its settings, called **hyperparameters**, can matter as much as the model design." },
      { t: "h", text: "The learning rate" },
      { t: "compare", left: { title: "Too high", items: ["Steps overshoot the valley", "Loss bounces around or shoots to infinity (NaN)", "The run diverges and you start over"] }, right: { title: "Too low", items: ["Steps are tiny and safe", "Training takes forever", "Can get stuck on flat plateaus"] } },
      { t: "p", text: "In practice, big models use a **schedule**: a short **warmup** where the learning rate ramps up from near zero (so early, chaotic gradients don't wreck the weights), then a slow **decay**, often a cosine curve, so the final steps are small and precise." },
      { t: "h", text: "Batches: how much data per step" },
      { t: "terms", items: [
        { term: "Full batch", def: "Compute the gradient over the entire dataset, then take one step. Accurate, but impossibly slow for billions of examples." },
        { term: "Stochastic (SGD)", def: "Use one random example per step. Fast but noisy." },
        { term: "Mini-batch", def: "The standard: average the gradient over a batch of, say, 32 to several million tokens. The noise even helps the model escape bad spots." },
        { term: "Epoch", def: "One full pass through the training data. Large language models often see most of their data only about once." },
      ] },
      { t: "h", text: "Momentum and Adam" },
      { t: "p", text: "Plain SGD treats every step independently, so it zig-zags across narrow valleys. **Momentum** keeps a running average of recent gradients, like a ball rolling downhill that builds speed in consistent directions and smooths out the zig-zags." },
      { t: "p", text: "**Adam** (Kingma & Ba, 2014) goes further. It keeps two running averages per weight: the gradient (momentum) and the squared gradient (how noisy that weight's gradient has been). Each weight effectively gets its own learning rate. Weights with consistently large gradients take smaller, careful steps, and rarely-updated weights take bigger ones. **AdamW**, Adam with decoupled weight decay, is the default optimizer for nearly every large language model." },
      { t: "code", label: "Adam's update for one weight", lang: "python", text: "m = β1 * m + (1 - β1) * g          # momentum: average gradient\nv = β2 * v + (1 - β2) * g * g      # average squared gradient\nm_hat = m / (1 - β1 ** t)          # bias correction for early steps\nv_hat = v / (1 - β2 ** t)\nw -= lr * m_hat / (sqrt(v_hat) + eps)" },
      { t: "note", kind: "warn", title: "Optimizers cost memory", text: "Adam stores two extra numbers, m and v, for every single weight, usually in 32-bit precision. For a 7-billion-parameter model that's 56 GB of optimizer state alone, before the weights, gradients, or activations. This is why training needs far more GPUs than running." },
      { t: "h", text: "Keeping training stable" },
      { t: "list", items: [
        "**Gradient clipping:** if the gradient's overall size exceeds a limit (often 1.0), scale it down so one bad batch can't blow up the weights.",
        "**Normalization layers:** keep each layer's outputs in a steady range so the next layer sees consistent inputs.",
        "**Loss curves:** engineers watch training and validation loss constantly. A sudden spike usually means the learning rate is too high or the data contains something broken.",
      ] },
    ],
    takeaways: [
      "The learning rate sets step size. Too high diverges, too low crawls. Warmup and decay schedules are standard.",
      "Mini-batches balance accurate gradients against speed.",
      "Momentum smooths steps; Adam gives each weight its own adaptive step size.",
      "Optimizer state can take more memory than the model itself.",
    ],
    quiz: [
      { q: "A training run's loss suddenly jumps to NaN after a few hundred steps. What's the most likely first fix?", options: ["Add more layers", "Lower the learning rate and/or add gradient clipping", "Train for more epochs", "Remove the validation set"], answer: 1, why: "Diverging loss usually means steps are too large. Smaller steps or clipped gradients stabilize it." },
      { q: "What does Adam track for each weight that plain SGD doesn't?", options: ["Its name and layer", "Running averages of its gradient and its squared gradient", "The training example that changed it most", "A copy of the original weight"], answer: 1, why: "Those two moments give each weight an adaptive step size." },
      { q: "Why use a learning-rate warmup at the start of training?", options: ["To save electricity", "Early gradients from random weights are chaotic, and big steps then can damage training", "Because GPUs need to heat up", "To make the first epoch shorter"], answer: 1, why: "Ramping up lets the optimizer's statistics settle before taking large steps." },
      { q: "Roughly how much memory does Adam's state (m and v in 32-bit floats) need for a 1-billion-parameter model?", options: ["1 GB", "4 GB", "8 GB", "32 GB"], answer: 2, why: "2 numbers × 4 bytes × 1 billion = 8 GB, on top of the weights and gradients." },
    ],
  },

  generalization: {
    hook: "A model that scores 100% on its training data might be the worst model you've built. The only score that matters is on data it has never seen.",
    blocks: [
      { t: "p", text: "Module 01 introduced **overfitting**: memorizing instead of learning. Now let's look at how professionals measure it and fight it, because a big network with millions of parameters can memorize almost any dataset if you let it." },
      { t: "h", text: "Three splits, three jobs" },
      { t: "terms", items: [
        { term: "Training set", def: "What the model learns from. Usually 80% or more of the data." },
        { term: "Validation set", def: "Used *during* development to choose hyperparameters and decide when to stop. The model never trains on it, but your decisions are tuned to it." },
        { term: "Test set", def: "Touched once, at the very end. Because you never tuned anything to it, it's an honest estimate of real-world performance." },
      ] },
      { t: "note", kind: "warn", title: "Data leakage", text: "If test examples sneak into training, even indirectly, the test score lies. Famous examples: duplicate images across splits, future information leaking into a stock predictor, and benchmark questions appearing on the internet text a language model was trained on. That last one is called **contamination**, and it's a real problem for judging LLMs." },
      { t: "h", text: "Reading the curves" },
      { t: "example", label: "Training vs. validation loss over time", text: "epoch   train   val\n  1     2.10    2.15     both falling: still learning\n  5     0.90    1.02     healthy gap\n 10     0.40    0.98     val flattening\n 20     0.05    1.40     train ↓, val ↑ : overfitting. Stop at epoch ~10." },
      { t: "p", text: "Stopping when validation loss stops improving is called **early stopping**, and it's one of the simplest, most effective defenses." },
      { t: "h", text: "Regularization: making memorizing harder" },
      { t: "list", items: [
        "**Weight decay (L2):** add a small penalty for large weights. The model prefers simple, smooth solutions over spiky ones that fit noise.",
        "**Dropout:** during training, randomly switch off a fraction of neurons (often 10–50%) each step. No neuron can rely on a specific partner, so the network learns redundant, robust features (Srivastava et al., 2014).",
        "**Data augmentation:** create varied copies of each example, like flipped, cropped, or recolored images. You used this in Teach the Machine.",
        "**More data:** the most reliable fix of all. Large language models trained on trillions of tokens barely overfit because they rarely see the same text twice.",
      ] },
      { t: "h", text: "Choosing the right metric" },
      { t: "p", text: "Accuracy can mislead. If 1% of patients have a disease, a model that always says \"healthy\" is 99% accurate and completely useless. Engineers use **precision** (of the cases it flagged, how many were right?), **recall** (of the real cases, how many did it catch?), and look at results broken down by group, like you did in the Bias Lab." },
      { t: "example", label: "Precision and recall", text: "100 real cases, model flags 80, of which 60 are real\nprecision = 60 / 80  = 75%   (when it says yes, it's right 75% of the time)\nrecall    = 60 / 100 = 60%   (it catches 60% of the real cases)" },
      { t: "note", kind: "key", title: "Benchmarks are a proxy", text: "A model that tops a leaderboard has learned to do well on *that test*. Whether that transfers to your real task is a separate question you should always check yourself." },
    ],
    takeaways: [
      "Train on the training set, tune on validation, report on a test set used once.",
      "A widening gap between training and validation loss signals overfitting.",
      "Weight decay, dropout, augmentation, early stopping, and more data all fight memorizing.",
      "Pick metrics that match the real goal. Accuracy alone can hide a useless model.",
    ],
    quiz: [
      { q: "Training loss keeps falling while validation loss starts rising. What should you do?", options: ["Train longer until both fall", "Stop around where validation loss was lowest, and consider more regularization", "Raise the learning rate", "Delete the validation set"], answer: 1, why: "Rising validation loss with falling training loss is overfitting. Early stopping and regularization address it." },
      { q: "You tried 50 hyperparameter settings and picked the one with the best test-set score. What's wrong?", options: ["Nothing, that's the standard method", "You tuned to the test set, so its score is no longer an honest estimate", "50 is too few settings", "Test sets should be bigger than training sets"], answer: 1, why: "Choosing based on the test set leaks it into your decisions. That's what the validation set is for." },
      { q: "A fraud detector catches 90 of 100 real frauds but also flags 900 legitimate purchases. Which is true?", options: ["High precision, low recall", "High recall (90%), low precision (about 9%)", "High precision and high recall", "It has 99% accuracy so it's great"], answer: 1, why: "Recall = 90/100. Precision = 90/(90+900) ≈ 9%. Customers would hate it." },
      { q: "What does dropout do during training?", options: ["Removes bad training examples", "Randomly disables a fraction of neurons each step so the network can't rely on any single one", "Deletes layers that aren't learning", "Lowers the learning rate over time"], answer: 1, why: "Random neuron dropout forces redundant, robust representations." },
    ],
  },
};
