import type { LessonContent } from "../lesson-types";

export const modelBuilding: Record<string, LessonContent> = {
  parameters: {
    hook: "\"A 70-billion-parameter model.\" You've seen numbers like that in headlines. By the end of this lesson you'll be able to compute one yourself from a model's config file.",
    blocks: [
      { t: "p", text: "A **parameter** is any number in the model that training adjusts: every weight in every matrix and every bias. Nothing else. The architecture (how many layers, how wide) is chosen by people and fixed. The parameters are what gets learned, and together they *are* the model." },
      { t: "compare", left: { title: "Parameters (learned)", items: ["Weights and biases", "Embedding vectors", "Normalization scales", "Billions of them, set by gradient descent"] }, right: { title: "Hyperparameters (chosen)", items: ["Number of layers, hidden size, heads", "Learning rate, batch size", "Vocabulary size, context length", "A few dozen, set by engineers"] } },
      { t: "h", text: "Counting a transformer" },
      { t: "p", text: "You already know the pieces from Module 06. Call the hidden size **d**, the number of layers **L**, and the vocabulary size **V**. Ignoring tiny bias and norm terms:" },
      { t: "example", label: "Parameter count for a GPT-style model", text: "Per block:\n  attention: Q, K, V, and output projections, each d × d  → 4d²\n  MLP: d → 4d and 4d → d                                  → 8d²\n  total per block                                         ≈ 12d²\n\nWhole model ≈ L × 12d²  +  V × d  (embeddings)" },
      { t: "example", label: "Check it on GPT-2 small: L = 12, d = 768, V = 50,257", text: "12 × 12 × 768²     = 84,934,656\n50,257 × 768       = 38,597,376\n1,024 positions × 768 = 786,432\n                   ≈ 124 million   ✓ the published size" },
      { t: "widget", id: "model-builder" },
      { t: "h", text: "Where the parameters live" },
      { t: "p", text: "In big models, almost everything is in the blocks, and two-thirds of each block is the MLP. Embeddings matter a lot for small models (31% of GPT-2 small) but very little for huge ones. The 12d² term grows with the *square* of width, which is why going from d = 768 to d = 12,288 (GPT-3) multiplies each block by 256." },
      { t: "h", text: "Parameters → memory → hardware" },
      { t: "example", label: "Memory just to hold the weights", text: "bytes = parameters × bytes per parameter\n\n7B model in 32-bit float (4 bytes): 28 GB\n7B model in 16-bit (2 bytes):       14 GB\n7B model in 4-bit (0.5 bytes):      3.5 GB  ← fits on a laptop GPU" },
      { t: "p", text: "Training needs far more. A common estimate for mixed-precision training with Adam is about **16 bytes per parameter** before activations: 16-bit weights and gradients, plus 32-bit master weights and two Adam moments. For 7 billion parameters, that's over 100 GB, more than any single consumer GPU, so training is split across many GPUs." },
      { t: "note", kind: "key", title: "More parameters isn't automatically better", text: "Chinchilla showed a 70B model can beat a 280B one if it's trained on enough data. Data quality, training length, and post-training often matter as much as raw size." },
    ],
    takeaways: [
      "Parameters are the numbers training learns. Hyperparameters are the settings people choose.",
      "A GPT-style transformer has about 12d² parameters per layer plus V × d for embeddings.",
      "Memory for weights = parameters × bytes per parameter.",
      "Training needs roughly 16 bytes per parameter with Adam, which is why it spans many GPUs.",
    ],
    quiz: [
      { q: "Which of these is a parameter, not a hyperparameter?", options: ["The learning rate", "The number of layers", "A single number in the attention query matrix", "The batch size"], answer: 2, why: "Parameters are learned values inside the model. The others are settings chosen before training." },
      { q: "Using the 12d² rule, about how many parameters are in the blocks of a model with 32 layers and d = 4,096?", options: ["About 400 million", "About 6.4 billion", "About 64 billion", "About 1.6 billion"], answer: 1, why: "32 × 12 × 4,096² ≈ 6.44 billion. Llama 2 7B has this shape (its MLP is sized a bit differently, landing near 6.5B in the blocks)." },
      { q: "How much memory do a 13-billion-parameter model's weights need in 16-bit precision?", options: ["13 GB", "26 GB", "52 GB", "6.5 GB"], answer: 1, why: "13 billion × 2 bytes = 26 GB." },
      { q: "Doubling the hidden size d (and nothing else) does what to the per-layer parameter count?", options: ["Doubles it", "Roughly quadruples it", "Leaves it the same", "Halves it"], answer: 1, why: "Per-layer parameters scale with d², so 2× width means about 4× parameters." },
    ],
  },

  "weights-on-disk": {
    hook: "Download an open model and you get a few giant files and a small text file. Open them up and there's no intelligence in sight: just named grids of numbers. Here's how to read them.",
    blocks: [
      { t: "p", text: "A trained model is stored as two things: a **config** that describes the architecture, and a set of **tensors**, the weights, each with a name, a shape, and a data type. Code that knows the architecture reads the config, builds empty layers, and fills them in from the file." },
      { t: "code", label: "config.json (trimmed, Llama-2-7B style)", lang: "json", text: "{\n  \"architectures\": [\"LlamaForCausalLM\"],\n  \"hidden_size\": 4096,\n  \"intermediate_size\": 11008,\n  \"num_hidden_layers\": 32,\n  \"num_attention_heads\": 32,\n  \"vocab_size\": 32000,\n  \"max_position_embeddings\": 4096,\n  \"rms_norm_eps\": 1e-05,\n  \"torch_dtype\": \"float16\"\n}" },
      { t: "h", text: "The state dict" },
      { t: "p", text: "The weights are a dictionary from tensor name to tensor, called the **state dict**. Names follow the module structure, so you can read the architecture straight off them." },
      { t: "code", label: "Tensor names and shapes (layer 0 of 32)", lang: "text", text: "model.embed_tokens.weight                  [32000, 4096]\nmodel.layers.0.input_layernorm.weight      [4096]\nmodel.layers.0.self_attn.q_proj.weight     [4096, 4096]\nmodel.layers.0.self_attn.k_proj.weight     [4096, 4096]\nmodel.layers.0.self_attn.v_proj.weight     [4096, 4096]\nmodel.layers.0.self_attn.o_proj.weight     [4096, 4096]\nmodel.layers.0.post_attention_layernorm.weight [4096]\nmodel.layers.0.mlp.gate_proj.weight        [11008, 4096]\nmodel.layers.0.mlp.up_proj.weight          [11008, 4096]\nmodel.layers.0.mlp.down_proj.weight        [4096, 11008]\n...  layers 1–31 repeat the same 9 tensors ...\nmodel.norm.weight                          [4096]\nlm_head.weight                             [32000, 4096]" },
      { t: "p", text: "Count it: each layer has 4 × 4096² attention weights plus 3 × 11008 × 4096 MLP weights, about 202 million. Times 32 layers, plus the embedding and LM head, is about **6.74 billion**: the \"7B.\" The three MLP matrices are a **SwiGLU** MLP: `down(silu(gate(x)) * up(x))`." },
      { t: "note", kind: "key", title: "Shape convention", text: "PyTorch stores a linear layer's weight as `[out_features, in_features]`. That's why `down_proj` is `[4096, 11008]`: it maps 11,008 back down to 4,096." },
      { t: "h", text: "File formats" },
      { t: "terms", items: [
        { term: ".safetensors", def: "The current standard on Hugging Face. A small JSON header lists every tensor's name, dtype, shape, and byte offset, followed by raw numbers. It can be memory-mapped, so loading is fast, and it can't contain executable code." },
        { term: ".bin / .pt (pickle)", def: "PyTorch's older format, built on Python's pickle. Loading an untrusted pickle can **run arbitrary code** on your machine, which is a real security risk." },
        { term: "GGUF", def: "A single-file format used by llama.cpp and tools built on it, designed for quantized models running on laptops and phones." },
        { term: "Shards", def: "Big models are split into several files, like `model-00001-of-00002.safetensors`, with an index file mapping each tensor to its shard." },
      ] },
      { t: "h", text: "Data types" },
      { t: "example", label: "How each number is stored", text: "float32  4 bytes  sign + 8-bit exponent + 23-bit fraction   (training master copy)\nfloat16  2 bytes  sign + 5-bit exponent + 10-bit fraction   (narrow range, can overflow)\nbfloat16 2 bytes  sign + 8-bit exponent +  7-bit fraction   (same range as fp32, less precision)\nint8     1 byte   integers −128…127 plus a scale factor\nint4     ½ byte   integers −8…7 plus a scale per group" },
      { t: "p", text: "**bfloat16** keeps float32's range by giving up precision, which is why it became the favorite for training: gradients rarely overflow, and neural networks tolerate a little rounding." },
      { t: "note", kind: "warn", title: "Open weights ≠ open source", text: "Releasing weights lets anyone run and fine-tune a model, but the training data and code are often not released, and licenses can restrict use. Always read a model's license before building on it." },
    ],
    takeaways: [
      "A model is a config (architecture) plus named weight tensors (the state dict).",
      "Tensor names mirror the module structure; shapes reveal hidden size, MLP size, and vocabulary.",
      "safetensors is safe and fast; pickle files can execute code; GGUF targets local inference.",
      "Data types trade memory for precision. bfloat16 keeps range, int4 shrinks the model 4× vs. fp16.",
    ],
    quiz: [
      { q: "A weight tensor is named `model.layers.17.mlp.up_proj.weight` with shape [11008, 4096]. What does it do?", options: ["Embeds tokens", "In layer 18, projects each token's 4,096-d vector up to 11,008 dimensions inside the MLP", "Stores attention scores", "Maps the final vector to the vocabulary"], answer: 1, why: "Layers are zero-indexed, it's in the MLP, and [out, in] means 4,096 → 11,008." },
      { q: "Why is .safetensors preferred over pickle-based .bin files for sharing models?", options: ["It compresses weights 10×", "It stores only raw tensors and metadata, so loading it can't execute hidden code", "It works only on GPUs", "It includes the training data"], answer: 1, why: "Pickle can run arbitrary code when loaded. safetensors is pure data." },
      { q: "Why did bfloat16 become popular for training, compared to float16?", options: ["It uses less memory", "It has float32's exponent range, so values rarely overflow, at the cost of precision", "It's more precise than float32", "It's an integer format"], answer: 1, why: "Both are 2 bytes, but bf16 spends its bits on range instead of precision." },
      { q: "From the config, what's the shape of `lm_head.weight` for a model with vocab_size 50,000 and hidden_size 2,048?", options: ["[2048, 2048]", "[50000, 2048]", "[2048, 8192]", "[50000]"], answer: 1, why: "The LM head maps a 2,048-d vector to one logit per vocabulary token: [out = 50,000, in = 2,048]." },
    ],
  },

  pretraining: {
    hook: "Training a frontier model can take thousands of GPUs running for months, and a single bad batch at week six can cost millions. Here's what actually happens inside that run.",
    blocks: [
      { t: "p", text: "**Pretraining** is the first and by far most expensive stage: teach a randomly initialized transformer to predict the next token on a huge, diverse corpus. Everything the model \"knows\" about language, facts, and reasoning patterns is learned here." },
      { t: "h", text: "1. Data" },
      { t: "list", ordered: true, items: [
        "**Collect:** web crawls (like Common Crawl), books, code repositories, academic papers, encyclopedias, and more.",
        "**Filter:** remove spam, boilerplate, low-quality pages, and toxic content, often using smaller classifier models to score quality.",
        "**Deduplicate:** remove near-identical documents. Duplicates waste compute and increase memorization.",
        "**Remove personal data and benchmarks:** scrub emails and phone numbers, and strip test questions to avoid contamination.",
        "**Mix:** choose proportions, like how much code versus prose. Data mix is one of the most closely guarded recipes in AI.",
        "**Tokenize:** convert everything into token IDs and pack them into fixed-length sequences.",
      ] },
      { t: "h", text: "2. The training loop" },
      { t: "code", label: "Pretraining, stripped to its core", lang: "python", text: "for step, batch in enumerate(loader):          # batch: (B, T) token IDs\n    inputs, targets = batch[:, :-1], batch[:, 1:]  # predict each next token\n    logits = model(inputs)                         # (B, T-1, vocab)\n    loss = cross_entropy(logits.flatten(0, 1), targets.flatten())\n    loss.backward()\n    clip_grad_norm_(model.parameters(), 1.0)\n    optimizer.step(); optimizer.zero_grad()\n    scheduler.step()                               # warmup, then cosine decay\n    if step % 1000 == 0: save_checkpoint(model, optimizer, step)" },
      { t: "p", text: "Notice the shift: inputs are tokens 1 to T−1 and targets are tokens 2 to T. Every position in every sequence is a training example, so one 4,096-token sequence teaches 4,095 predictions at once." },
      { t: "h", text: "3. Spreading it across thousands of GPUs" },
      { t: "terms", items: [
        { term: "Data parallel", def: "Every GPU holds a copy of the model and processes different batches; gradients are averaged across GPUs each step." },
        { term: "Tensor parallel", def: "Split individual weight matrices across GPUs, so each computes part of every layer." },
        { term: "Pipeline parallel", def: "Put different layers on different GPUs, passing activations along like an assembly line." },
        { term: "Sharded optimizer (ZeRO/FSDP)", def: "Split weights, gradients, and Adam state across GPUs so no single one holds the full 16 bytes per parameter." },
      ] },
      { t: "h", text: "4. Keeping it alive" },
      { t: "p", text: "At this scale, hardware fails constantly. Runs save **checkpoints** regularly so they can restart. Engineers watch the loss curve around the clock, and **loss spikes** sometimes force a rollback to an earlier checkpoint and skipping the batches that caused trouble." },
      { t: "example", label: "A reality check on cost", text: "Training compute ≈ 6 × N × D\nLlama 2 7B: 6 × 7×10⁹ × 2×10¹² tokens ≈ 8.4 × 10²² FLOPs\nMeta reported about 184,000 GPU-hours on A100s for the 7B model." },
      { t: "h", text: "What comes out" },
      { t: "p", text: "The result is a **base model**: a powerful autocomplete. Ask it a question and it might continue with more questions, because on the internet, questions are often followed by more questions. Turning it into a helpful assistant is the next lesson." },
      { t: "note", kind: "warn", title: "Data is an ethics question too", text: "Whether models may train on copyrighted books, art, and code without permission is being fought in courts right now. So is whether creators should be able to opt out. Module 03's privacy and integrity lessons apply at industrial scale." },
    ],
    takeaways: [
      "Pretraining teaches next-token prediction on trillions of filtered, deduplicated tokens.",
      "Each sequence yields a prediction at every position: inputs shifted by one are the targets.",
      "Data, tensor, pipeline, and sharded parallelism spread training across thousands of GPUs.",
      "The output is a base model: knowledgeable, but not yet an assistant.",
    ],
    quiz: [
      { q: "Why do pretraining pipelines deduplicate their data?", options: ["To make the dataset look bigger", "Duplicates waste compute and make the model more likely to memorize and regurgitate text", "Tokenizers can't handle repeats", "To remove all code"], answer: 1, why: "Repeated text is learned more strongly, increasing memorization and wasting training budget." },
      { q: "In the training loop, why are the targets the input shifted one position left?", options: ["To save memory", "Each position learns to predict the token that comes right after it", "So the model sees the answer first", "To apply dropout"], answer: 1, why: "Next-token prediction: position t predicts token t+1." },
      { q: "A model is too big for any single GPU's memory, even for its weights. Which technique directly helps?", options: ["Data parallelism alone", "Tensor or pipeline parallelism, or sharding the model across GPUs", "A higher learning rate", "A bigger batch size"], answer: 1, why: "Plain data parallelism keeps a full copy on every GPU. Splitting the model is required." },
      { q: "You prompt a base model (no fine-tuning) with \"What is photosynthesis?\" What's a likely result?", options: ["A polished, friendly explanation every time", "It may continue the text in any plausible way, such as listing more quiz questions", "It refuses", "An error"], answer: 1, why: "Base models continue text. Following instructions is taught later in post-training." },
    ],
  },

  "post-training": {
    hook: "Same weights, two very different personalities. A base model rambles; the assistant built from it answers clearly and declines harmful requests. The difference is a few percent more training on very carefully chosen data.",
    blocks: [
      { t: "p", text: "**Post-training** turns a base model into an assistant. It uses far less compute than pretraining but has an outsized effect on how the model behaves. The landmark recipe was InstructGPT (Ouyang et al., 2022), which became the basis of ChatGPT." },
      { t: "h", text: "Stage 1: supervised fine-tuning (SFT)" },
      { t: "p", text: "Train on tens of thousands of high-quality example conversations, often written by people: an instruction and an ideal response. Same next-token loss as pretraining, but the loss is usually only computed on the response tokens, so the model learns to *answer*, not to imitate the user." },
      { t: "code", label: "One SFT example, as a chat template", lang: "text", text: "<|system|>You are a helpful tutor for high school students.<|end|>\n<|user|>Explain photosynthesis in two sentences.<|end|>\n<|assistant|>Plants use sunlight to turn carbon dioxide and water into sugar,\nwhich stores energy. Oxygen is released as a by-product.<|end|>" },
      { t: "h", text: "Stage 2: learning from preferences" },
      { t: "p", text: "It's easier for people to *compare* two answers than to write a perfect one. So the model generates several responses, people pick which they prefer, and that preference data trains the model further." },
      { t: "terms", items: [
        { term: "RLHF", def: "Reinforcement learning from human feedback. Train a separate **reward model** to predict which answer people prefer, then use reinforcement learning (often PPO) to push the assistant toward high-reward answers, with a penalty for drifting too far from the SFT model." },
        { term: "DPO", def: "Direct preference optimization (Rafailov et al., 2023). Skips the separate reward model and adjusts the model directly so preferred answers become more likely than rejected ones. Simpler and now very common." },
        { term: "RLAIF / constitutional AI", def: "Use an AI model, guided by a written set of principles, to generate some of the preference judgments (Bai et al., 2022). Scales feedback beyond what human raters can provide." },
      ] },
      { t: "note", kind: "warn", title: "Reward hacking", text: "Models optimize what's measured, not what's meant. If raters reward longer or more confident answers, the model learns to be long-winded or overconfident. A reward model is a proxy, and pushing too hard on a proxy breaks it." },
      { t: "h", text: "Fine-tuning on your own: LoRA" },
      { t: "p", text: "Updating all 7 billion weights to teach a model your school's writing style needs the full training memory budget. **LoRA** (low-rank adaptation, Hu et al., 2021) freezes the original weights and learns a small correction for selected matrices instead." },
      { t: "example", label: "LoRA on one 4096 × 4096 matrix", text: "Original:  W (4096 × 4096) = 16,777,216 frozen weights\nLoRA:      W + B·A,  B is 4096 × r,  A is r × 4096\nWith r = 8: 2 × 4096 × 8 = 65,536 trainable weights  (0.4% of the original)\n\nThe small A and B matrices can be saved as a few-megabyte \"adapter\" file." },
      { t: "p", text: "**QLoRA** combines this with a 4-bit quantized base model, making it possible to fine-tune large models on a single GPU." },
      { t: "h", text: "Other post-training ingredients" },
      { t: "list", items: [
        "**Safety training:** examples of declining harmful requests, plus red-teaming to find failure cases before release.",
        "**Tool use and reasoning data:** examples of calling tools and working through problems step by step, the foundation for Module 08.",
        "**Evals:** large test suites checked after every change, because improving one behavior often breaks another.",
      ] },
    ],
    takeaways: [
      "SFT teaches the format and style of good answers from example conversations.",
      "RLHF and DPO use human (or AI) preference comparisons to shape behavior further.",
      "Optimizing a proxy reward too hard leads to reward hacking.",
      "LoRA fine-tunes with a tiny fraction of trainable weights by learning a low-rank correction.",
    ],
    quiz: [
      { q: "During supervised fine-tuning, why is the loss usually computed only on the assistant's tokens?", options: ["To save electricity", "So the model learns to produce good responses rather than to imitate the user's messages", "Because user messages are private", "It isn't; loss is always on everything"], answer: 1, why: "Masking the prompt focuses learning on the responses you want the model to generate." },
      { q: "What does the reward model in RLHF do?", options: ["Pays the human raters", "Predicts which of two responses people would prefer, giving a score used to train the assistant", "Generates training data from the web", "Filters toxic words"], answer: 1, why: "It's trained on preference comparisons and acts as an automated judge during RL." },
      { q: "A LoRA adapter with rank r = 16 is applied to a 2048 × 2048 matrix. How many trainable parameters does it add?", options: ["32", "65,536", "4,194,304", "2,048"], answer: 1, why: "B is 2048 × 16 and A is 16 × 2048: 2 × 2048 × 16 = 65,536." },
      { q: "Raters consistently prefer longer answers, and after RLHF the model pads every response. This is an example of…", options: ["Overfitting the pretraining data", "Reward hacking: optimizing a flawed proxy for quality", "Quantization error", "A tokenizer bug"], answer: 1, why: "The model learned what the reward signal favored, not what people actually wanted." },
    ],
  },

  quantization: {
    hook: "A model that needs a 28 GB server GPU in 32-bit can run on a phone. The trick is to store each weight with fewer bits, and accept a tiny bit of rounding error.",
    blocks: [
      { t: "p", text: "**Quantization** means storing numbers with fewer bits. Weights trained in 16 or 32 bits are mapped to 8-bit or 4-bit integers plus a few scale factors. The model gets 2–8× smaller and usually faster, because running a model is often limited by how fast weights can be read from memory, not by math." },
      { t: "h", text: "How it works" },
      { t: "example", label: "Symmetric int8 quantization of one group of weights", text: "weights:  [0.82, −0.41, 0.05, −1.27]\nscale  = max(|w|) / 127 = 1.27 / 127 = 0.01\nq      = round(w / scale)        = [82, −41, 5, −127]   (stored as int8)\ndequantized = q × scale          = [0.82, −0.41, 0.05, −1.27]\n\nWith 4 bits (range −7…7): scale = 1.27/7 ≈ 0.181\nq = [5, −2, 0, −7] → [0.91, −0.36, 0.00, −1.27]   ← visible rounding error" },
      { t: "p", text: "Quantizing a whole matrix with one scale is too crude: a single large value (an **outlier**) forces a big scale, crushing all the small weights to zero. So modern methods use a separate scale for each small **group** of weights, often 32–128 at a time." },
      { t: "h", text: "Popular methods" },
      { t: "terms", items: [
        { term: "Round-to-nearest", def: "Just round each group, as above. Works well at 8 bits; noticeably hurts quality at 4 bits for some models." },
        { term: "GPTQ", def: "Quantizes weights one column at a time and adjusts the remaining weights to compensate for the rounding error, using a small calibration dataset (Frantar et al., 2022)." },
        { term: "AWQ", def: "Finds the small fraction of weights that matter most, judged by activation size, and protects them during quantization (Lin et al., 2023)." },
        { term: "GGUF k-quants", def: "The llama.cpp family of formats, like Q4_K_M, mixing bit widths across layers for a good size and quality balance on laptops." },
      ] },
      { t: "h", text: "Running a model on your own computer" },
      { t: "example", label: "Will it fit? (weights only; add 1–2 GB for KV cache and overhead)", text: "Model  fp16     8-bit    4-bit\n 3B    6 GB     3 GB     1.5 GB   phone or any laptop\n 7B   14 GB     7 GB     3.5 GB   most laptops with 8–16 GB\n13B   26 GB    13 GB     6.5 GB   gaming GPU or 16 GB Mac\n70B  140 GB    70 GB      35 GB   workstation or multiple GPUs" },
      { t: "p", text: "Tools like llama.cpp, Ollama, and LM Studio download a quantized GGUF file and run it entirely on your device. Nothing you type leaves your computer, which connects straight back to Module 03's privacy lesson." },
      { t: "h", text: "The tradeoff" },
      { t: "list", items: [
        "**8-bit:** usually nearly indistinguishable from 16-bit.",
        "**4-bit:** the sweet spot for local use. Small quality loss, often hardest on math, code, and very small models.",
        "**2–3 bit:** quality usually drops noticeably. An active research area.",
        "**Distillation** is a different shrinking strategy: train a small \"student\" model to imitate a large \"teacher.\"",
      ] },
      { t: "note", kind: "key", title: "Why smaller is often faster", text: "Generating each token means reading every weight from memory once. A 4-bit model reads a quarter of the bytes of a 16-bit one, so on memory-bound hardware it can generate tokens close to 4× faster." },
    ],
    takeaways: [
      "Quantization stores weights in fewer bits plus scale factors, shrinking models 2–8×.",
      "Per-group scales handle outliers; GPTQ and AWQ reduce error further.",
      "Memory ≈ parameters × bits ÷ 8. A 4-bit 7B model needs about 3.5 GB.",
      "Local models keep your data on your device and are often memory-bandwidth limited.",
    ],
    quiz: [
      { q: "Roughly how much memory do the weights of a 30-billion-parameter model need at 4 bits?", options: ["7.5 GB", "15 GB", "30 GB", "120 GB"], answer: 1, why: "30 billion × 0.5 bytes = 15 GB." },
      { q: "Why do quantization methods use a separate scale for each small group of weights?", options: ["To make the file bigger", "One outlier would otherwise force a large scale that rounds most small weights to zero", "Groups run on different GPUs", "Integers can't be negative"], answer: 1, why: "Per-group scales confine an outlier's damage to its own group." },
      { q: "A weight group has max |w| = 0.7 and is quantized to int8 symmetrically (−127…127). What's the scale?", options: ["0.7", "≈ 0.0055", "127", "≈ 0.1"], answer: 1, why: "scale = 0.7 / 127 ≈ 0.0055." },
      { q: "Why can a 4-bit model generate text faster than a 16-bit version on the same laptop?", options: ["It skips layers", "Generation is limited by reading weights from memory, and 4-bit weights are a quarter of the bytes", "It uses a smaller vocabulary", "It runs at a lower temperature"], answer: 1, why: "Token-by-token generation is usually memory-bandwidth bound." },
    ],
  },
};
