import type { LessonContent } from "../lesson-types";

export const transformers: Record<string, LessonContent> = {
  embeddings: {
    hook: "A computer can't read the word \"king.\" It can only read numbers. So how does a model end up knowing that king is to queen as man is to woman?",
    blocks: [
      { t: "p", text: "Before a language model sees any text, two things happen. A **tokenizer** chops the text into pieces and gives each piece an ID number. Then an **embedding** layer turns each ID into a long list of numbers, a vector, that captures what the token means." },
      { t: "h", text: "Step 1: tokenizing" },
      { t: "p", text: "Most modern models use **byte-pair encoding (BPE)** or a close relative. It starts with individual bytes, then repeatedly merges the most common adjacent pair into a new token, until the vocabulary hits a target size, often 32,000 to 200,000 tokens. Common words become a single token. Rare words get split into familiar pieces." },
      { t: "example", label: "How a BPE tokenizer might split text", text: "\"The students studied photosynthesis.\"\n→ [\"The\", \" students\", \" studied\", \" photos\", \"ynthesis\", \".\"]\n→ [791, 4236, 20041, 14851, 74767, 13]     (made-up IDs)\n\nNote the leading spaces: \" students\" and \"students\" are different tokens." },
      { t: "note", kind: "key", title: "Tokens explain strange failures", text: "Because the model sees `\" strawberry\"` as one or two chunks, not ten letters, counting the r's means reasoning about letters it never directly sees. Tokenization also explains why some languages cost more tokens, and money, per sentence than English." },
      { t: "h", text: "Step 2: embedding" },
      { t: "p", text: "The **embedding matrix** has one row per token in the vocabulary. Row 4236 is the vector for \" students\". For GPT-2 small, each vector has 768 numbers, so the matrix is 50,257 × 768, almost 39 million parameters just to look up tokens." },
      { t: "p", text: "Nobody hand-writes these numbers. They start random and are learned by backpropagation along with everything else. Training pushes tokens that appear in similar contexts toward similar vectors, because that helps predict the next token." },
      { t: "h", text: "Meaning as direction" },
      { t: "p", text: "Two vectors are compared with **cosine similarity**: the cosine of the angle between them. 1 means pointing the same way, 0 means unrelated, −1 means opposite. In a well-trained embedding space, \"teacher\" and \"professor\" point in similar directions and \"teacher\" and \"volcano\" don't." },
      { t: "example", label: "The famous analogy (word2vec, Mikolov et al., 2013)", text: "vector(\"king\") − vector(\"man\") + vector(\"woman\") ≈ vector(\"queen\")\n\nThe difference between man and woman is roughly a consistent direction,\nand adding it to \"king\" lands near \"queen\"." },
      { t: "p", text: "That analogy came from an older, simpler model, but the idea carries over: **meaning becomes geometry**. Directions in the space can correspond to concepts like gender, tense, or formality. Researchers who study model internals, called **interpretability**, look for exactly these directions." },
      { t: "h", text: "Where am I in the sentence?" },
      { t: "p", text: "Embeddings alone don't say *where* a token sits. \"Dog bites man\" and \"man bites dog\" contain the same tokens. So models add **position information**. GPT-2 learned a separate position embedding for each of its 1,024 slots. Most current models use **RoPE** (rotary position embeddings), which rotates each vector by an angle that depends on its position, so attention can tell how far apart two tokens are." },
      { t: "note", kind: "warn", title: "Embeddings carry bias too", text: "Embeddings learn from human text, so they absorb its associations. Early studies found occupation words leaning toward one gender in embedding space. The Bias Lab's lesson applies here: the model mirrors its data." },
    ],
    takeaways: [
      "A tokenizer turns text into token IDs. BPE merges frequent pairs into a fixed vocabulary.",
      "The embedding matrix maps each token ID to a learned vector (one row per token).",
      "Similar meanings end up as similar directions, measured with cosine similarity.",
      "Position information, like RoPE, tells the model where each token sits.",
    ],
    quiz: [
      { q: "A model has a vocabulary of 32,000 tokens and a hidden size of 4,096. How many parameters are in its embedding matrix?", options: ["36,096", "About 131 million", "About 4 billion", "32,000"], answer: 1, why: "32,000 × 4,096 = 131,072,000 parameters, one row of 4,096 numbers per token." },
      { q: "How do embedding vectors get their values?", options: ["Linguists assign them from a dictionary", "They start random and are learned through backpropagation like other weights", "They're copied from a thesaurus", "They're the token's ID repeated"], answer: 1, why: "Embeddings are ordinary parameters, trained to help predict the next token." },
      { q: "Two embedding vectors have a cosine similarity of 0.92. What does that suggest?", options: ["The tokens are probably used in very similar contexts", "The tokens are spelled the same", "One token is 92% longer", "They're opposites"], answer: 0, why: "High cosine similarity means the vectors point in nearly the same direction, which comes from similar usage." },
      { q: "Why does a transformer need position information added?", options: ["To count the tokens", "Because attention by itself treats the input as an unordered set, so \"dog bites man\" and \"man bites dog\" would look the same", "To make the model smaller", "To translate between languages"], answer: 1, why: "Without positions, the same tokens in a different order would produce the same result." },
    ],
  },

  attention: {
    hook: "\"The trophy didn't fit in the suitcase because **it** was too big.\" You instantly know \"it\" means the trophy. Attention is how a model figures that out, and it's the idea that launched every modern AI chatbot.",
    blocks: [
      { t: "p", text: "In 2017, eight researchers at Google published *Attention Is All You Need* (Vaswani et al.), introducing the **transformer**. Its core idea, **self-attention**, lets every token look at every other token and decide which ones matter for understanding it. Earlier models read one word at a time and struggled to remember far-back context. Attention sees the whole sentence at once." },
      { t: "h", text: "Queries, keys, and values" },
      { t: "p", text: "Each token's embedding is multiplied by three learned weight matrices to make three new vectors. A helpful analogy is a library search." },
      { t: "terms", items: [
        { term: "Query (Q)", def: "What this token is looking for. For \"it\": *I'm a pronoun; which noun do I refer to?*" },
        { term: "Key (K)", def: "What each token advertises about itself. For \"trophy\": *I'm a physical object that could be big.*" },
        { term: "Value (V)", def: "The information a token hands over if it's chosen. The actual content that gets mixed in." },
      ] },
      { t: "h", text: "The four steps" },
      { t: "list", ordered: true, items: [
        "**Score:** dot every query with every key. A high dot product means \"this key matches what I'm looking for.\"",
        "**Scale:** divide by √d (the square root of the key length) so scores don't get huge as vectors get longer.",
        "**Softmax:** turn each row of scores into weights that are positive and add to 1.",
        "**Mix:** each token's output is the weighted average of all the value vectors.",
      ] },
      { t: "example", label: "The formula from the paper", text: "Attention(Q, K, V) = softmax( Q Kᵀ / √d ) V\n\nFor n tokens: Q Kᵀ is an n × n grid of scores. Every token scores every token." },
      { t: "widget", id: "attention" },
      { t: "h", text: "Masking: no peeking at the future" },
      { t: "p", text: "A model generating text must not see tokens that haven't been written yet. **Causal masking** sets the scores for future positions to −∞ before the softmax, so their weights become exactly 0. Each token can only attend to itself and earlier tokens. That's the triangle you see in the grid above." },
      { t: "h", text: "Many heads" },
      { t: "p", text: "One attention pattern can't capture everything. So transformers run several attention **heads** in parallel, each with its own Q, K, V matrices. GPT-2 small has 12 heads per layer. Researchers have found heads that track grammar, heads that link pronouns to nouns, and **induction heads** that spot repeated patterns and copy what came next last time (Olsson et al., 2022). Their outputs are joined back together and mixed with one more matrix." },
      { t: "note", kind: "warn", title: "The cost: n²", text: "Every token scores every other token, so doubling the context length quadruples the attention work. That's why long context windows were hard and expensive, and why techniques like FlashAttention, which reorders the math to use GPU memory efficiently, were such a big deal." },
      { t: "code", label: "Self-attention in 8 lines", lang: "python", text: "import torch, math\n\ndef attention(x, Wq, Wk, Wv):\n    Q, K, V = x @ Wq, x @ Wk, x @ Wv                    # (n, d) each\n    scores = Q @ K.T / math.sqrt(K.shape[-1])            # (n, n)\n    mask = torch.triu(torch.ones_like(scores), 1).bool()\n    scores = scores.masked_fill(mask, float('-inf'))     # no looking ahead\n    weights = torch.softmax(scores, dim=-1)              # rows sum to 1\n    return weights @ V                                   # (n, d)" },
    ],
    takeaways: [
      "Self-attention lets every token weigh every earlier token when building its meaning.",
      "Queries ask, keys advertise, values carry content. Scores are Q·K, scaled by √d, softmaxed.",
      "Causal masking blocks attention to future tokens during generation.",
      "Multiple heads learn different relationships. Cost grows with the square of context length.",
    ],
    quiz: [
      { q: "In self-attention, what determines how much token A attends to token B?", options: ["Their distance in the sentence only", "The dot product of A's query with B's key, after scaling and softmax", "Whether B is a noun", "B's value vector length"], answer: 1, why: "Attention weights come from query-key similarity, normalized by softmax." },
      { q: "Why are scores divided by √d before the softmax?", options: ["To make the model smaller", "Large dot products push softmax toward all-or-nothing weights with tiny gradients; scaling keeps them in a trainable range", "To convert them to percentages", "It's required to apply the mask"], answer: 1, why: "Dot products grow with vector length. Scaling keeps softmax from saturating." },
      { q: "In a causal (decoder) transformer, which tokens can position 5 attend to?", options: ["All positions", "Positions 1 through 5", "Only position 4", "Positions 5 onward"], answer: 1, why: "The causal mask blocks future positions, so a token sees itself and everything before it." },
      { q: "Context goes from 4,000 to 16,000 tokens. Roughly how much more work does the attention score grid take?", options: ["4×", "8×", "16×", "The same"], answer: 2, why: "The grid is n × n. 4× the tokens means 4² = 16× the scores." },
    ],
  },

  "transformer-block": {
    hook: "GPT-2, Llama, Claude, Gemini: under the branding they share one repeating unit. Learn to draw a single transformer block and you've drawn most of every frontier model.",
    blocks: [
      { t: "p", text: "A transformer language model is a **stack of identical blocks**. GPT-2 small stacks 12; GPT-3 stacks 96. Each block takes in one vector per token and outputs one vector per token of the same size, slightly refined. The input flows through like this:" },
      { t: "example", label: "One decoder block (pre-norm, as in GPT-2 and Llama)", text: "x ──► LayerNorm ──► Multi-head attention ──►(+)──► x′\n│                                          ▲\n└──────────────── residual ────────────────┘\n\nx′ ─► LayerNorm ─► MLP (expand 4×, GELU, shrink) ─►(+)─► output\n│                                                   ▲\n└───────────────────── residual ────────────────────┘" },
      { t: "h", text: "The four parts" },
      { t: "terms", items: [
        { term: "Attention", def: "Moves information *between* tokens. This is where \"it\" learns it refers to \"trophy.\"" },
        { term: "MLP (feed-forward)", def: "Processes each token *on its own*. Usually expands from d to 4d dimensions, applies a nonlinearity like GELU or SwiGLU, then shrinks back. Research suggests much of a model's factual recall is stored in these layers." },
        { term: "Residual connection", def: "Adds the block's input to its output: `x + f(x)`. Each block only has to learn a *change*. It also gives gradients a direct highway backward, which is how 100-layer stacks stay trainable (He et al., 2015)." },
        { term: "Layer normalization", def: "Rescales each token's vector to a steady mean and spread so values don't drift as they pass through dozens of blocks." },
      ] },
      { t: "h", text: "The residual stream" },
      { t: "p", text: "Interpretability researchers describe the running vector for each token as a **residual stream**: a shared workspace. Every attention head and MLP reads from it and writes a small update back. By the last block, the vector for the final token holds everything the model needs to predict what comes next." },
      { t: "h", text: "From last vector to next token" },
      { t: "p", text: "After the final block, one more matrix, the **unembedding** or **LM head**, turns the last token's vector into a score, called a **logit**, for every token in the vocabulary. Softmax turns logits into probabilities. Many models reuse the embedding matrix here, which is called **weight tying**." },
      { t: "code", label: "A GPT-style block, nearly complete", lang: "python", text: "class Block(nn.Module):\n    def __init__(self, d, heads):\n        super().__init__()\n        self.ln1 = nn.LayerNorm(d)\n        self.attn = nn.MultiheadAttention(d, heads, batch_first=True)\n        self.ln2 = nn.LayerNorm(d)\n        self.mlp = nn.Sequential(nn.Linear(d, 4 * d), nn.GELU(), nn.Linear(4 * d, d))\n\n    def forward(self, x, causal_mask):\n        h = self.ln1(x)\n        x = x + self.attn(h, h, h, attn_mask=causal_mask)[0]   # residual 1\n        x = x + self.mlp(self.ln2(x))                         # residual 2\n        return x" },
      { t: "h", text: "Three families" },
      { t: "list", items: [
        "**Decoder-only** (GPT, Llama, Claude): causal attention, generates text left to right. Nearly every chatbot.",
        "**Encoder-only** (BERT): attends in both directions. Great for understanding and classifying text, not for generating it.",
        "**Encoder-decoder** (the original 2017 transformer, T5): an encoder reads the input, a decoder writes the output. Common in translation.",
      ] },
      { t: "note", kind: "key", title: "Modern tweaks, same skeleton", text: "Newer models swap in RMSNorm for LayerNorm, SwiGLU for GELU, RoPE for learned positions, and grouped-query attention to save memory. Some use **mixture-of-experts** MLPs, where a router sends each token to a few of many expert MLPs. The block diagram above still describes them." },
    ],
    takeaways: [
      "A transformer is a stack of identical blocks: attention, then an MLP, each wrapped in a residual connection and normalization.",
      "Attention mixes information across tokens; the MLP processes each token independently.",
      "Residual connections let each block add a small update and keep deep stacks trainable.",
      "The LM head turns the final vector into logits over the vocabulary.",
    ],
    quiz: [
      { q: "What is the main job of the MLP sublayer, compared to attention?", options: ["It moves information between tokens", "It transforms each token's vector independently, and appears to store much factual knowledge", "It tokenizes the input", "It applies the causal mask"], answer: 1, why: "Attention is the only part that mixes across positions. The MLP works per token." },
      { q: "Why do residual connections make very deep transformers trainable?", options: ["They remove the need for attention", "They give gradients a direct path backward and let each block learn only a small change", "They reduce the vocabulary size", "They make the model run on CPUs"], answer: 1, why: "x + f(x) keeps an identity path, so signals and gradients don't vanish through many layers." },
      { q: "A model's final vector for the last token goes through the LM head. What comes out?", options: ["A single predicted word", "A logit for every token in the vocabulary", "The attention weights", "A new embedding matrix"], answer: 1, why: "The LM head produces one score per vocabulary token; softmax turns them into probabilities." },
      { q: "Which architecture is best suited for a chatbot that writes long answers?", options: ["Encoder-only, like BERT", "Decoder-only, like GPT or Llama", "A single perceptron", "A convolutional image model"], answer: 1, why: "Decoder-only models with causal attention generate text token by token." },
    ],
  },

  decoding: {
    hook: "The model doesn't output a word. It outputs a probability for every one of 100,000 possible tokens. *Which* one gets picked is a separate decision, and it changes everything about how the AI sounds.",
    blocks: [
      { t: "p", text: "Generation is a loop: run the model, get a probability distribution over the next token, **pick one**, append it, repeat. The picking step is called **decoding** or **sampling**, and it's controlled by settings you can often change yourself." },
      { t: "h", text: "Greedy decoding" },
      { t: "p", text: "Always pick the single most likely token. It's predictable, which is good for math and code, but on open-ended writing it tends to loop and repeat itself, because the most likely continuation of a repetitive sentence is often more repetition." },
      { t: "h", text: "Temperature" },
      { t: "p", text: "Before the softmax, every logit is divided by the **temperature** T. Below 1 sharpens the distribution toward the top choice. Above 1 flattens it so unlikely tokens get picked more often. T → 0 becomes greedy." },
      { t: "example", label: "Same logits, different temperatures", text: "logits:      cat 2.0   dog 1.0   car 0.1\nT = 0.5  →   cat 86%   dog 12%   car 2%\nT = 1.0  →   cat 66%   dog 24%   car 10%\nT = 2.0  →   cat 50%   dog 30%   car 19%" },
      { t: "h", text: "Top-k and top-p" },
      { t: "terms", items: [
        { term: "Top-k", def: "Keep only the k most likely tokens, renormalize, then sample. With k = 40, token #41 can never appear no matter how high the temperature." },
        { term: "Top-p (nucleus)", def: "Keep the smallest set of tokens whose probabilities add up to at least p, such as 0.9 (Holtzman et al., 2019). When the model is confident, that's 1–2 tokens; when it's unsure, it might be dozens. It adapts in a way top-k can't." },
      ] },
      { t: "widget", id: "sampling" },
      { t: "h", text: "Matching settings to the task" },
      { t: "compare", left: { title: "Low temperature (0–0.3)", items: ["Code, math, data extraction", "Answers you want reproducible", "Summaries that must stay faithful"] }, right: { title: "Higher temperature (0.7–1.0)", items: ["Brainstorming and creative writing", "Generating many varied options", "Dialogue that shouldn't sound robotic"] } },
      { t: "note", kind: "warn", title: "Temperature isn't a truth dial", text: "Lowering temperature makes the model pick its top guess more consistently. If its top guess is a hallucination, low temperature makes it confidently, consistently wrong. Fact-checking still applies." },
      { t: "h", text: "Speed tricks" },
      { t: "p", text: "Each new token needs a full pass through the model, which is slow. Two common speedups: the **KV cache** stores every previous token's keys and values so they aren't recomputed each step, and **speculative decoding** lets a small, fast model draft several tokens that the big model checks all at once." },
    ],
    takeaways: [
      "Generation repeats: predict a distribution, pick a token, append, repeat.",
      "Greedy is predictable but repetitive. Temperature divides logits to sharpen or flatten the distribution.",
      "Top-k keeps a fixed number of candidates; top-p keeps a probability mass, so it adapts to confidence.",
      "Low temperature means consistency, not correctness.",
    ],
    quiz: [
      { q: "Logits are [3.0, 1.0]. What happens to the top token's probability as temperature goes from 1.0 to 0.25?", options: ["It decreases", "It increases toward 100%", "It stays the same", "It becomes exactly 50%"], answer: 1, why: "Dividing by a small T stretches the gap between logits, sharpening the distribution." },
      { q: "With top-p = 0.9, the model is very confident: the top token has 95% probability. How many tokens can be sampled?", options: ["Exactly 90", "Just 1", "All of them", "10"], answer: 1, why: "The top token alone already covers 0.9 of the probability mass." },
      { q: "You want an AI to extract dates from 500 documents into a spreadsheet, the same way every time. Which settings fit best?", options: ["Temperature 1.5, top-p 1.0", "Temperature near 0", "Temperature 1.0, top-k 1,000", "It doesn't matter"], answer: 1, why: "Extraction needs consistency. Near-zero temperature makes outputs nearly deterministic." },
      { q: "What does the KV cache save during generation?", options: ["The user's chat history on a server", "Previously computed keys and values, so each new token doesn't recompute attention inputs for the whole prefix", "The model's weights", "A list of banned words"], answer: 1, why: "Earlier tokens' K and V don't change, so caching them avoids redundant work." },
    ],
  },

  scaling: {
    hook: "In 2019, GPT-2's biggest version had 1.5 billion parameters and was considered almost too powerful to release. A year later, GPT-3 had 175 billion. What happened in between was the discovery of a rule: bigger, predictably, means better.",
    blocks: [
      { t: "p", text: "Researchers found that a language model's loss falls along a smooth, predictable curve as you increase three things: **parameters (N)**, **training tokens (D)**, and **compute (C)**. Plotted on log-log axes, the curves are nearly straight lines. These are **scaling laws** (Kaplan et al., 2020)." },
      { t: "note", kind: "key", title: "Why that's a big deal", text: "Predictable means plannable. A lab can train small models cheaply, fit the curve, and forecast how good a model 100× bigger will be before spending millions of dollars on it." },
      { t: "h", text: "The compute rule of thumb" },
      { t: "example", label: "Training compute", text: "C ≈ 6 × N × D    floating-point operations (FLOPs)\n\n(≈2 per parameter per token for the forward pass, ≈4 for the backward pass)\n\nGPT-3: 6 × 175 billion × 300 billion tokens ≈ 3.15 × 10²³ FLOPs" },
      { t: "h", text: "Chinchilla: most models were undertrained" },
      { t: "p", text: "In 2022, DeepMind's Chinchilla paper (Hoffmann et al.) found that for a fixed compute budget, the best results come from scaling parameters and data together, at roughly **20 training tokens per parameter**. By that rule, GPT-3 should have been trained on about 3.5 trillion tokens instead of 300 billion. Chinchilla, at 70 billion parameters trained on 1.4 trillion tokens, beat models several times its size." },
      { t: "p", text: "Since then, many labs train *past* that point on purpose. A smaller model trained on far more data, like Llama 2 7B on 2 trillion tokens, costs more to train but is much cheaper to run for millions of users." },
      { t: "h", text: "Emergent abilities, and a debate" },
      { t: "p", text: "Some skills, like multi-step arithmetic, seemed to appear suddenly once models crossed a size threshold. Other researchers argued much of that suddenness comes from all-or-nothing scoring and looks smoother with better metrics (Schaeffer et al., 2023). It's an open question, and a good example of experts disagreeing in public." },
      { t: "h", text: "Context windows" },
      { t: "p", text: "The **context window** is how many tokens the model can attend to at once: GPT-2 had 1,024, GPT-3 had 2,048, and some current models handle hundreds of thousands or more. Longer windows cost more in two ways: attention work grows with n², and the KV cache grows with n." },
      { t: "example", label: "KV cache size per token (no sharing tricks)", text: "2 (K and V) × layers × hidden size × bytes per number\n\nLlama 2 7B: 2 × 32 × 4096 × 2 bytes (fp16) ≈ 0.5 MB per token\n4,096-token context ≈ 2 GB of cache per conversation" },
      { t: "note", kind: "warn", title: "Long context isn't perfect memory", text: "Studies found models often use information at the start and end of a long prompt better than information in the middle (Liu et al., 2023, \"Lost in the Middle\"). Put the most important instructions and facts where the model is most likely to use them." },
    ],
    takeaways: [
      "Loss improves predictably as parameters, data, and compute grow. These are scaling laws.",
      "Training compute ≈ 6 × parameters × tokens.",
      "Chinchilla: scale data with size, about 20 tokens per parameter for compute-optimal training.",
      "Longer context windows cost n² attention and a growing KV cache.",
    ],
    quiz: [
      { q: "Roughly how many FLOPs does it take to train a 1-billion-parameter model on 20 billion tokens?", options: ["2 × 10¹⁰", "1.2 × 10²⁰", "6 × 10⁹", "1 × 10³⁰"], answer: 1, why: "6 × 10⁹ × 2 × 10¹⁰ = 1.2 × 10²⁰ FLOPs." },
      { q: "By the Chinchilla rule of thumb, how many training tokens is compute-optimal for a 10-billion-parameter model?", options: ["10 billion", "About 200 billion", "10 trillion", "500 million"], answer: 1, why: "About 20 tokens per parameter: 20 × 10 billion = 200 billion." },
      { q: "Why might a company deliberately train a small model on far more tokens than Chinchilla recommends?", options: ["It's cheaper to train", "The model is cheaper and faster to run for many users, even if training costs more", "Scaling laws don't apply to small models", "It needs fewer GPUs to train"], answer: 1, why: "Inference costs scale with model size and happen millions of times. Overtraining a small model trades training cost for cheaper use." },
      { q: "A model's context window doubles. What happens to its KV cache memory for a full context?", options: ["It stays the same", "It roughly doubles", "It grows 4×", "It halves"], answer: 1, why: "The KV cache stores K and V per token, so it grows linearly with the number of tokens." },
    ],
  },
};
